# Generated by Django 2.0.13 on 2019-05-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('phone_number', models.CharField(max_length=11)),
                ('contract_date', models.DateTimeField(verbose_name='contract date')),
            ],
        ),
        migrations.CreateModel(
            name='companies_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('report_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='useful_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
