# Generated by Django 2.0.13 on 2019-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='contract_date',
            field=models.DateField(verbose_name='contract date'),
        ),
    ]
