# Generated by Django 2.0.13 on 2019-06-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0003_clients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='date of creation')),
            ],
        ),
    ]
